name: Build and test

on:
  push:
    branches: [live]
  pull_request:
    branches: [live]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [8, 10, 12]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm test
        run: |
          npm test
        env:
          CI: true
      - name: Code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
  build:
    name: Build and package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm pack
        run: |
          npm pack
        env:
          CI: true
      - name: Upload npm package
        uses: actions/upload-artifact@v2
        with:
          name: npm-package
          path: ./*.tgz
